### ISSUE TITLE
복사 버튼 추가 

### ISSUE THREAD

**Issue by 10001if** [opencloset/barcode#2]
![2015-12-29 1 40 16](https://cloud.githubusercontent.com/assets/4696328/12029603/3fe45d0c-ae32-11e5-8878-91e7c46b9a15.png)
드래그 하여 복사를 하는 방법이 불편할 것 같아서요. 복사 버튼을 만들어 주시면 훨씬 쉽게 사용할 수 있을 것 같아요. ^^

**Comment by aanoaa** [comment]
클립보드에 복사하는건 아마 flash 써야 하지 않나요?

**Comment by aanoaa** [comment]
https://github.com/zenorocha/clipboard.js 라고 좋은게 있네요.

**Comment by keedi** [comment]
@aanoaa clipboard.js 좋네요 ㅎㅎ

**Comment by keedi** [comment]
더불어 다음  문서도 참고했습니다.
- [StackOverflow - How do I copy to the clipboard in JavaScript?](http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript)
- [Javascript: Copy To Clipboard Cross Browser](http://www.deluxeblogtips.com/2010/06/javascript-copy-to-clipboard.html)

**Comment by keedi** [comment]
`document.execCommand('copy')` 함수를 사용하는 것이 가장 간단한 방법으로 보입니다. 다만 테스트 결과 `disabled`한 `input` 요소는 선택이 안되기 때문에 `disabled` 대신 `readonly` 를 사용해야 합니다.

**Comment by keedi** [comment]
구현 완료한 화면입니다.

![screenshot-barcode theopencloset net 2015-12-30 21-10-38](https://cloud.githubusercontent.com/assets/138451/12050511/f92c9a1a-af39-11e5-9024-8073e519ba2c.png)

**Comment by keedi** [comment]
구현 및 배포 완료했습니다.

@10001if 
브라우저 캐시 이슈가 있을 수 있으니 새로고침 하셔야 합니다. :)

**Comment by 10001if** [comment]
네! 확인했습니다. 감사합니다~ 오늘 조심히 잘 다녀오셔요 ^^
